Chore.create!([
  {title: "Garbage Out Sunday 1", day: "Sunday"},
  {title: "Garbage Out Sunday 2", day: "Sunday"},
  {title: "Garbage Out Sunday 3", day: "Sunday"},
  {title: "Put Away Dishes Monday Morning", day: "Monday"},
  {title: "Do Dishes Monday Evening", day: "Monday"},
  {title: "Garbage In Monday 1", day: "Monday"},
  {title: "Garbage In Monday 2", day: "Monday"},
  {title: "Do Dishes Monday Morning", day: "Monday"},
  {title: "Do Dishes Tuesday Morning", day: "Tuesday"},
  {title: "Put Away Dishes Tuesday Morning", day: "Tuesday"},
  {title: "Garbage Out Tuesday 1", day: "Tuesday"},
  {title: "Garbage Out Tuesday 2", day: "Tuesday"},
  {title: "Garbage Out Tuesday 3", day: "Tuesday"},
  {title: "Put Away Dishes Tuesday Evening", day: "Tuesday"},
  {title: "Put Away Dishes Monday Evening", day: "Monday"},
  {title: "Do Dishes Tuesday Evening", day: "Tuesday"},
  {title: "Garbage In Wednesday 1", day: "Wednesday"},
  {title: "Garbage In Wednesday 2", day: "Wednesday"},
  {title: "Do Dishes Wednesday Morning", day: "Wednesday"},
  {title: "Put Away Dishes Wednesday Morning", day: "Wednesday"},
  {title: "Do Dishes Wednesday Evening", day: "Wednesday"},
  {title: "Put Away Dishes Wednesday Evening", day: "Wednesday"},
  {title: "Garbage Out Thursday 1", day: "Thursday"},
  {title: "Garbage Out Thursday 2", day: "Thursday"},
  {title: "Garbage Out Thursday 3", day: "Thursday"},
  {title: "Do Dishes Thursday Morning", day: "Thursday"},
  {title: "Put Away Dishes Thursday Morning", day: "Thursday"},
  {title: "Do Dishes Thursday Evening", day: "Thursday"},
  {title: "Put Away Dishes Thursday Evening", day: "Thursday"},
  {title: "Garbage In Friday 1", day: "Friday"},
  {title: "Garbage In Friday 2", day: "Friday"},
  {title: "Do Dishes Friday Morning", day: "Friday"},
  {title: "Put Away Dishes Friday Morning", day: "Friday"},
  {title: "Do Dishes Friday Evening", day: "Friday"},
  {title: "Put Away Dishes Friday Evening", day: "Friday"},
  {title: "Do Dishes Saturday Morning", day: "Saturday"},
  {title: "Put Away Dishes Saturday Morning", day: "Saturday"},
  {title: "Do Dishes Saturday Evening", day: "Saturday"},
  {title: "Put Away Dishes Saturday Evening", day: "Saturday"},
  {title: "Do Dishes Sunday Morning", day: "Sunday"},
  {title: "Put Away Dishes Sunday Evening", day: "Sunday"},
  {title: "Put Away Dishes Sunday Morning", day: "Sunday"},
  {title: "Do Dishes Sunday Evening", day: "Sunday"}
])

User.create!([
  {name: "Nathan H", uid: "6186377", email: "hsieh.nathan@gmail.com", photo: "https://avatars.githubusercontent.com/u/6186377?", admin: false},
  {name: "Matt Petrie", uid: "3870201", email: "matthew.petrie@gmail.com", photo: "https://avatars.githubusercontent.com/u/3870201?", admin: true}
])
