Chore.create!([
  {title: "Garbage In Monday", day: "Monday", crew: 2},
  {title: "Do Dishes Monday Morning", day: "Monday", crew: 1},
  {title: "Put Away Dishes Monday Morning", day: "Monday", crew: 1},
  {title: "Do Dishes Monday Evening", day: "Monday", crew: 1},
  {title: "Put Away Dishes Monday Evening", day: "Monday", crew: 1},
  {title: "Garbage Out Tuesday", day: "Tuesday", crew: 3},
  {title: "Do Dishes Tuesday Morning", day: "Tuesday", crew: 1},
  {title: "Put Away Dishes Tuesday Morning", day: "Tuesday", crew: 1},
  {title: "Do Dishes Tuesday Evening", day: "Tuesday", crew: 1},
  {title: "Put Away Dishes Tuesday Evening", day: "Tuesday", crew: 1},
  {title: "Garbage In Wednesday", day: "Wednesday", crew: 2},
  {title: "Do Dishes Wednesday Morning", day: "Wednesday", crew: 1},
  {title: "Put Away Dishes Wednesday Morning", day: "Wednesday", crew: 1},
  {title: "Do Dishes Wednesday Evening", day: "Wednesday", crew: 1},
  {title: "Put Away Dishes Wednesday Evening", day: "Wednesday", crew: 1},
  {title: "Garbage Out Thursday", day: "Thursday", crew: 3},
  {title: "Do Dishes Thursday Morning", day: "Thursday", crew: 1},
  {title: "Put Away Dishes Thursday Morning", day: "Thursday", crew: 1},
  {title: "Do Dishes Thursday Evening", day: "Thursday", crew: 1},
  {title: "Put Away Dishes Thursday Evening", day: "Thursday", crew: 1},
  {title: "Garbage In Friday", day: "Friday", crew: 2},
  {title: "Do Dishes Friday Morning", day: "Friday", crew: 1},
  {title: "Put Away Dishes Friday Morning", day: "Friday", crew: 1},
  {title: "Do Dishes Friday Evening", day: "Friday", crew: 1},
  {title: "Put Away Dishes Friday Evening", day: "Friday", crew: 1},
  {title: "Do Dishes Saturday Morning", day: "Saturday", crew: 1},
  {title: "Put Away Dishes Saturday Morning", day: "Saturday", crew: 1},
  {title: "Do Dishes Saturday Evening", day: "Saturday", crew: 1},
  {title: "Put Away Dishes Saturday Evening", day: "Saturday", crew: 1},
  {title: "Garbage Out Sunday", day: "Sunday", crew: 3},
  {title: "Do Dishes Sunday Morning", day: "Sunday", crew: 1},
  {title: "Put Away Dishes Sunday Morning", day: "Sunday", crew: 1},
  {title: "Put Away Dishes Sunday Evening", day: "Sunday", crew: 1},
  {title: "Do Dishes Sunday Evening", day: "Sunday", crew: 1}
])

User.create!([
  {name: "Nathan H", uid: "6186377", email: "hsieh.nathan@gmail.com", photo: "https://avatars.githubusercontent.com/u/6186377?", admin: false},
  {name: "Matt Petrie", uid: "3870201", email: "matthew.petrie@gmail.com", photo: "https://avatars.githubusercontent.com/u/3870201?", admin: true}
])
